spring:
  config:
    activate:
      on-profile: dev-carlos
  datasource:
    url: jdbc:postgresql://localhost:5432/users-demo
    username: postgres
    password: febrero18
    driver-class-name: org.postgresql.Driver