spring:
  config:
    activate:
      on-profile: local
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:usersdb
    username: sa
    password:
    h2:
      console:
        enabled: true
    hibernate:
      ddl-auto: update
    jpa:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      show-sql: true
  enabled:
    traceability:
      allMethods: ${ENABLED_TRACEABILITY_ALL_METHODS:true}