spring:
  config:
    activate:
      on-profile: dev-santi
  datasource:
    url: jdbc:postgresql://localhost:5555/users-demo
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver